// Company job boards to scan, plus the role keyword filter.
// Ported/adapted from the MIT-licensed career-ops project (santifer/career-ops).
// Only Greenhouse / Ashby / Lever boards are API-scannable. Add your own freely —
// a wrong slug just errors out for that one company (non-fatal).

export interface Portal {
  name: string;
  /** Greenhouse boards API URL. */
  api?: string;
  /** Ashby or Lever public careers URL (the scanner derives the API from it). */
  careersUrl?: string;
}

const gh = (slug: string): string =>
  `https://boards-api.greenhouse.io/v1/boards/${slug}/jobs`;
const ashby = (slug: string): string => `https://jobs.ashbyhq.com/${slug}`;
const lever = (slug: string): string => `https://jobs.lever.co/${slug}`;

export const PORTALS: Portal[] = [
  // --- Greenhouse ---
  { name: "Anthropic", api: gh("anthropic") },
  { name: "Intercom", api: gh("intercom") },
  { name: "Airtable", api: gh("airtable") },
  { name: "Vercel", api: gh("vercel") },
  { name: "Temporal", api: gh("temporal") },
  { name: "Glean", api: gh("gleanwork") },
  { name: "Arize AI", api: gh("arizeai") },
  { name: "RunPod", api: gh("runpod") },
  { name: "Hume AI", api: gh("humeai") },
  { name: "PolyAI", api: gh("polyai") },
  { name: "Parloa", api: gh("parloa") },
  { name: "Speechmatics", api: gh("speechmatics") },
  { name: "Databricks", api: gh("databricks") },
  { name: "Discord", api: gh("discord") },
  { name: "Reddit", api: gh("reddit") },
  { name: "Robinhood", api: gh("robinhood") },
  { name: "Figma", api: gh("figma") },
  { name: "Samsara", api: gh("samsara") }, // IoT / connected devices
  // Verified boards (batch 2)
  { name: "Stripe", api: gh("stripe") },
  { name: "Coinbase", api: gh("coinbase") },
  { name: "Instacart", api: gh("instacart") },
  { name: "Dropbox", api: gh("dropbox") },
  { name: "GitLab", api: gh("gitlab") },
  { name: "Cloudflare", api: gh("cloudflare") },
  { name: "Twilio", api: gh("twilio") },
  { name: "Brex", api: gh("brex") },
  { name: "Asana", api: gh("asana") },
  { name: "Pinterest", api: gh("pinterest") },
  { name: "Lyft", api: gh("lyft") },
  { name: "Affirm", api: gh("affirm") },
  { name: "Chime", api: gh("chime") },
  { name: "Gusto", api: gh("gusto") },
  { name: "Flexport", api: gh("flexport") },
  { name: "Amplitude", api: gh("amplitude") },
  { name: "MongoDB", api: gh("mongodb") },
  { name: "Cockroach Labs", api: gh("cockroachlabs") },
  { name: "Postman", api: gh("postman") },
  { name: "Grafana Labs", api: gh("grafanalabs") },
  { name: "Scale AI", api: gh("scaleai") },
  { name: "Faire", api: gh("faire") },
  { name: "Airbnb", api: gh("airbnb") },
  { name: "Okta", api: gh("okta") },
  { name: "Roblox", api: gh("roblox") },
  { name: "Betterment", api: gh("betterment") },
  { name: "Squarespace", api: gh("squarespace") },
  { name: "SoFi", api: gh("sofi") },
  { name: "Toast", api: gh("toast") },
  { name: "Nextdoor", api: gh("nextdoor") },
  { name: "DoorDash", api: gh("doordashusa") },
  { name: "Datadog", api: gh("datadog") },
  { name: "Elastic", api: gh("elastic") },
  { name: "Waymo", api: gh("waymo") },
  { name: "Verkada", api: gh("verkada") },
  { name: "Rubrik", api: gh("rubrik") },
  { name: "Carta", api: gh("carta") },
  { name: "Marqeta", api: gh("marqeta") },
  { name: "Gemini", api: gh("gemini") },
  { name: "Checkr", api: gh("checkr") },
  { name: "Webflow", api: gh("webflow") },
  { name: "Calendly", api: gh("calendly") },

  // Verified boards (GitHub batch)
  { name: "Abnormalsecurity", api: gh("abnormalsecurity") },
  { name: "Adyen", api: gh("adyen") },
  { name: "Astranis", api: gh("astranis") },
  { name: "Attentive", api: gh("attentive") },
  { name: "Bitpanda", api: gh("bitpanda") },
  { name: "Bitso", api: gh("bitso") },
  { name: "Bitwarden", api: gh("bitwarden") },
  { name: "Braze", api: gh("braze") },
  { name: "Calm", api: gh("calm") },
  { name: "Careem", api: gh("careem") },
  { name: "Cerebral", api: gh("cerebral") },
  { name: "Clickhouse", api: gh("clickhouse") },
  { name: "Coalition", api: gh("coalition") },
  { name: "Cognism", api: gh("cognism") },
  { name: "Collectivehealth", api: gh("collectivehealth") },
  { name: "Comet", api: gh("comet") },
  { name: "Commercetools", api: gh("commercetools") },
  { name: "Coreweave", api: gh("coreweave") },
  { name: "Cresta", api: gh("cresta") },
  { name: "Customerio", api: gh("customerio") },
  { name: "Cybereason", api: gh("cybereason") },
  { name: "Dashlane", api: gh("dashlane") },
  { name: "Descript", api: gh("descript") },
  { name: "Dremio", api: gh("dremio") },
  { name: "Fastly", api: gh("fastly") },
  { name: "Fetch", api: gh("fetch") },
  { name: "Fictiv", api: gh("fictiv") },
  { name: "Figure", api: gh("figure") },
  { name: "Fivetran", api: gh("fivetran") },
  { name: "Formbio", api: gh("formbio") },
  { name: "Found", api: gh("found") },
  { name: "Galileo", api: gh("galileo") },
  { name: "Ghost", api: gh("ghost") },
  { name: "Gocardless", api: gh("gocardless") },
  { name: "Gongio", api: gh("gongio") },
  { name: "Grailed", api: gh("grailed") },
  { name: "Greenhouse", api: gh("greenhouse") },
  { name: "Groww", api: gh("groww") },
  { name: "Guild", api: gh("guild") },
  { name: "Hackerrank", api: gh("hackerrank") },
  { name: "Hightouch", api: gh("hightouch") },
  { name: "Hometap", api: gh("hometap") },
  { name: "Hover", api: gh("hover") },
  { name: "Huntress", api: gh("huntress") },
  { name: "Imbue", api: gh("imbue") },
  { name: "Imply", api: gh("imply") },
  { name: "Instabase", api: gh("instabase") },
  { name: "Invisibletech", api: gh("invisibletech") },
  { name: "Iterable", api: gh("iterable") },
  { name: "Karat", api: gh("karat") },
  { name: "Kickstarter", api: gh("kickstarter") },
  { name: "Klaviyo", api: gh("klaviyo") },
  { name: "Labelbox", api: gh("labelbox") },
  { name: "Lattice", api: gh("lattice") },
  { name: "Launchdarkly", api: gh("launchdarkly") },
  { name: "Ledgy", api: gh("ledgy") },
  { name: "Lithic", api: gh("lithic") },
  { name: "Make", api: gh("make") },
  { name: "Mattermost", api: gh("mattermost") },
  { name: "Medium", api: gh("medium") },
  { name: "Mercari", api: gh("mercari") },
  { name: "Mesh", api: gh("mesh") },
  { name: "Mixpanel", api: gh("mixpanel") },
  { name: "Modernhealth", api: gh("modernhealth") },
  { name: "Monzo", api: gh("monzo") },
  { name: "Mos", api: gh("mos") },
  { name: "N26", api: gh("n26") },
  { name: "Netskope", api: gh("netskope") },
  { name: "Newrelic", api: gh("newrelic") },
  { name: "Nuro", api: gh("nuro") },
  { name: "Offerup", api: gh("offerup") },
  { name: "Orca", api: gh("orca") },
  { name: "Oscar", api: gh("oscar") },
  { name: "Pagerduty", api: gh("pagerduty") },
  { name: "Peloton", api: gh("peloton") },
  { name: "Planetscale", api: gh("planetscale") },
  { name: "Relaytherapeutics", api: gh("relaytherapeutics") },
  { name: "Remote", api: gh("remote") },
  { name: "Roofstock", api: gh("roofstock") },
  { name: "Salesloft", api: gh("salesloft") },
  { name: "Seesaw", api: gh("seesaw") },
  { name: "Showpad", api: gh("showpad") },
  { name: "Singlestore", api: gh("singlestore") },
  { name: "Smartsheet", api: gh("smartsheet") },
  { name: "Spothero", api: gh("spothero") },
  { name: "Stabilityai", api: gh("stabilityai") },
  { name: "Stockx", api: gh("stockx") },
  { name: "Sumologic", api: gh("sumologic") },
  { name: "Tailscale", api: gh("tailscale") },
  { name: "Textio", api: gh("textio") },
  { name: "Thinkingmachines", api: gh("thinkingmachines") },
  { name: "Togetherai", api: gh("togetherai") },
  { name: "Treasuryprime", api: gh("treasuryprime") },
  { name: "Truveta", api: gh("truveta") },
  { name: "Turing", api: gh("turing") },
  { name: "Twitch", api: gh("twitch") },
  { name: "Udacity", api: gh("udacity") },
  { name: "Udemy", api: gh("udemy") },
  { name: "Upgrade", api: gh("upgrade") },
  { name: "Workato", api: gh("workato") },
  { name: "Worldlabs", api: gh("worldlabs") },
  { name: "Wrike", api: gh("wrike") },
  { name: "Yugabyte", api: gh("yugabyte") },
  { name: "Zoominfo", api: gh("zoominfo") },
  { name: "Zscaler", api: gh("zscaler") },

  // --- Ashby ---
  { name: "ElevenLabs", careersUrl: ashby("elevenlabs") },
  { name: "Deepgram", careersUrl: ashby("deepgram") },
  { name: "Vapi", careersUrl: ashby("vapi") },
  { name: "Sierra", careersUrl: ashby("sierra") },
  { name: "Decagon", careersUrl: ashby("decagon") },
  { name: "Lindy", careersUrl: ashby("lindy") },
  { name: "n8n", careersUrl: ashby("n8n") },
  { name: "Zapier", careersUrl: ashby("zapier") },
  { name: "Cohere", careersUrl: ashby("cohere") },
  { name: "LangChain", careersUrl: ashby("langchain") },
  { name: "Pinecone", careersUrl: ashby("pinecone") },
  { name: "Notion", careersUrl: ashby("notion") },
  { name: "Ramp", careersUrl: ashby("ramp") },
  { name: "Linear", careersUrl: ashby("linear") },
  { name: "Mercury", careersUrl: ashby("mercury") },
  { name: "Vanta", careersUrl: ashby("vanta") },
  { name: "PostHog", careersUrl: ashby("posthog") },
  { name: "Cursor", careersUrl: ashby("cursor") },
  { name: "Replit", careersUrl: ashby("replit") },
  { name: "Baseten", careersUrl: ashby("baseten") },
  { name: "Supabase", careersUrl: ashby("supabase") },
  { name: "Resend", careersUrl: ashby("resend") },
  { name: "Railway", careersUrl: ashby("railway") },
  { name: "Neon", careersUrl: ashby("neon") },
  { name: "Browserbase", careersUrl: ashby("browserbase") },

  // Verified boards (GitHub batch)
  { name: "1password", careersUrl: ashby("1password") },
  { name: "Abridge", careersUrl: ashby("abridge") },
  { name: "Airbyte", careersUrl: ashby("airbyte") },
  { name: "Airwallex", careersUrl: ashby("airwallex") },
  { name: "Ankorstore", careersUrl: ashby("ankorstore") },
  { name: "Anyscale", careersUrl: ashby("anyscale") },
  { name: "Applied", careersUrl: ashby("applied") },
  { name: "Astronomer", careersUrl: ashby("astronomer") },
  { name: "Atlan", careersUrl: ashby("atlan") },
  { name: "Benchling", careersUrl: ashby("benchling") },
  { name: "Brightwheel", careersUrl: ashby("brightwheel") },
  { name: "Capchase", careersUrl: ashby("capchase") },
  { name: "Capsule", careersUrl: ashby("capsule") },
  { name: "Cedar", careersUrl: ashby("cedar") },
  { name: "Cerebras", careersUrl: ashby("cerebras") },
  { name: "Circle", careersUrl: ashby("circle") },
  { name: "Clearco", careersUrl: ashby("clearco") },
  { name: "Clickup", careersUrl: ashby("clickup") },
  { name: "Cognition", careersUrl: ashby("cognition") },
  { name: "Confluent", careersUrl: ashby("confluent") },
  { name: "Craftdocs", careersUrl: ashby("craftdocs") },
  { name: "Crusoe", careersUrl: ashby("crusoe") },
  { name: "Docker", careersUrl: ashby("docker") },
  { name: "Dust", careersUrl: ashby("dust") },
  { name: "Fireworks", careersUrl: ashby("fireworks") },
  { name: "Flink", careersUrl: ashby("flink") },
  { name: "Flock", careersUrl: ashby("flock") },
  { name: "Fullstory", careersUrl: ashby("fullstory") },
  { name: "Gamma", careersUrl: ashby("gamma") },
  { name: "Handshake", careersUrl: ashby("handshake") },
  { name: "Harvey", careersUrl: ashby("harvey") },
  { name: "Headway", careersUrl: ashby("headway") },
  { name: "Hopper", careersUrl: ashby("hopper") },
  { name: "Insitro", careersUrl: ashby("insitro") },
  { name: "Kin", careersUrl: ashby("kin") },
  { name: "Knock", careersUrl: ashby("knock") },
  { name: "Kong", careersUrl: ashby("kong") },
  { name: "Leapsome", careersUrl: ashby("leapsome") },
  { name: "Lovable", careersUrl: ashby("lovable") },
  { name: "Materialize", careersUrl: ashby("materialize") },
  { name: "Maven", careersUrl: ashby("maven") },
  { name: "Mercor", careersUrl: ashby("mercor") },
  { name: "Miro", careersUrl: ashby("miro") },
  { name: "Modal", careersUrl: ashby("modal") },
  { name: "Moderntreasury", careersUrl: ashby("moderntreasury") },
  { name: "Montecarlodata", careersUrl: ashby("montecarlodata") },
  { name: "Motherduck", careersUrl: ashby("motherduck") },
  { name: "Neptune", careersUrl: ashby("neptune") },
  { name: "Nerdwallet", careersUrl: ashby("nerdwallet") },
  { name: "Nubank", careersUrl: ashby("nubank") },
  { name: "Numeral", careersUrl: ashby("numeral") },
  { name: "Openai", careersUrl: ashby("openai") },
  { name: "Openevidence", careersUrl: ashby("openevidence") },
  { name: "Opensea", careersUrl: ashby("opensea") },
  { name: "Overjet", careersUrl: ashby("overjet") },
  { name: "Oyster", careersUrl: ashby("oyster") },
  { name: "Patreon", careersUrl: ashby("patreon") },
  { name: "Perplexity", careersUrl: ashby("perplexity") },
  { name: "Physicalintelligence", careersUrl: ashby("physicalintelligence") },
  { name: "Plaid", careersUrl: ashby("plaid") },
  { name: "Pleo", careersUrl: ashby("pleo") },
  { name: "Poolside", careersUrl: ashby("poolside") },
  { name: "Poshmark", careersUrl: ashby("poshmark") },
  { name: "Prefect", careersUrl: ashby("prefect") },
  { name: "Quantcast", careersUrl: ashby("quantcast") },
  { name: "Rasa", careersUrl: ashby("rasa") },
  { name: "Render", careersUrl: ashby("render") },
  { name: "Rula", careersUrl: ashby("rula") },
  { name: "Runway", careersUrl: ashby("runway") },
  { name: "Sardine", careersUrl: ashby("sardine") },
  { name: "Sentry", careersUrl: ashby("sentry") },
  { name: "Snowflake", careersUrl: ashby("snowflake") },
  { name: "Sondermind", careersUrl: ashby("sondermind") },
  { name: "Substack", careersUrl: ashby("substack") },
  { name: "Suno", careersUrl: ashby("suno") },
  { name: "Surfshark", careersUrl: ashby("surfshark") },
  { name: "Svix", careersUrl: ashby("svix") },
  { name: "Synctera", careersUrl: ashby("synctera") },
  { name: "Thumbtack", careersUrl: ashby("thumbtack") },
  { name: "Union", careersUrl: ashby("union") },
  { name: "Unit", careersUrl: ashby("unit") },
  { name: "Velocity", careersUrl: ashby("velocity") },
  { name: "Wayflyer", careersUrl: ashby("wayflyer") },
  { name: "Wealthsimple", careersUrl: ashby("wealthsimple") },
  { name: "Weaviate", careersUrl: ashby("weaviate") },
  { name: "Writer", careersUrl: ashby("writer") },
  { name: "Zip", careersUrl: ashby("zip") },

  // --- Lever ---
  { name: "Netlify", careersUrl: lever("netlify") },
  { name: "Voiceflow", careersUrl: lever("voiceflow") },
  { name: "Palantir", careersUrl: lever("palantir") },
  { name: "Kavak", careersUrl: lever("kavak") },
  { name: "Spotify", careersUrl: lever("spotify") },
  // Verified boards (GitHub batch)
  { name: "Benchsci", careersUrl: lever("benchsci") },
  { name: "Chownow", careersUrl: lever("chownow") },
  { name: "Cred", careersUrl: lever("cred") },
  { name: "Greenlight", careersUrl: lever("greenlight") },
  { name: "Highspot", careersUrl: lever("highspot") },
  { name: "Jumpcloud", careersUrl: lever("jumpcloud") },
  { name: "Leantaas", careersUrl: lever("leantaas") },
  { name: "Meesho", careersUrl: lever("meesho") },
  { name: "Mindtickle", careersUrl: lever("mindtickle") },
  { name: "Nium", careersUrl: lever("nium") },
  { name: "Outreach", careersUrl: lever("outreach") },
  { name: "Porter", careersUrl: lever("porter") },
  { name: "Ro", careersUrl: lever("ro") },
  { name: "Sysdig", careersUrl: lever("sysdig") },
  { name: "Tinybird", careersUrl: lever("tinybird") },
  { name: "Viget", careersUrl: lever("viget") },
  { name: "Wealthfront", careersUrl: lever("wealthfront") },
  { name: "Zeta", careersUrl: lever("zeta") },
  { name: "Zilliz", careersUrl: lever("zilliz") },
];

// Role keyword filter: a title must contain at least one positive keyword and
// no negative keyword (case-insensitive).
export const TITLE_FILTER = {
  positive: [
    // SDE / general
    "Software Engineer",
    "Software Development",
    "SDE",
    "Software Developer",
    // Backend
    "Backend",
    "Back-End",
    "Back End",
    "Server",
    "Distributed Systems",
    "Platform Engineer",
    "Infrastructure Engineer",
    // Full stack
    "Full Stack",
    "Full-Stack",
    "Fullstack",
    // Frontend
    "Frontend",
    "Front-End",
    "Front End",
    "Web Engineer",
    "Web Developer",
    "UI Engineer",
    // IoT / embedded
    "IoT",
    "Embedded",
    "Firmware",
    "Device",
    "Hardware",
    // AI / ML
    "AI",
    "ML",
    "Machine Learning",
    "Deep Learning",
    "LLM",
    "GenAI",
    "Generative AI",
    "NLP",
    "MLOps",
    "AI Engineer",
    "ML Engineer",
    "Applied AI",
    "Applied Scientist",
    "Data Engineer",
  ],
  negative: [
    "Intern",
    "Internship",
    "Manager",
    "Director",
    "VP",
    "Vice President",
    "Head of",
    "Sales",
    "Business Development",
    "Marketing",
    "Recruiter",
    "Recruiting",
    "Account Executive",
    "Designer",
    "Counsel",
    "Legal",
    "Finance",
    "People Partner",
    "Talent",
  ],
};

// JobSpy scanner — pulls LinkedIn + Indeed (best-effort; may be blocked on
// datacenter IPs). Runs in addition to the reliable ATS scan.
export const JOBSPY = {
  // Off by default — set ENABLE_JOBSPY=true in .env to turn on (best run locally).
  enabled: process.env.ENABLE_JOBSPY === "true",
  sites: ["linkedin", "indeed"] as const,
  location: "India",
  countryIndeed: "india",
  resultsWanted: 20,
  // Search terms for the target role families (fresher level is filtered after).
  searchTerms: [
    "Software Engineer",
    "Backend Developer",
    "Full Stack Developer",
    "Frontend Developer",
    "Machine Learning Engineer",
  ],
};

// Experience-level filter — keep only fresher / entry-level roles.
export const EXPERIENCE = {
  // Master switch. Set false to keep all experience levels.
  fresherOnly: true,
  // A role passes if its required experience is <= this (years).
  maxYears: 2,
  // Seniority markers in the TITLE → excluded outright.
  seniorMarkers: [
    "Senior",
    "Sr",
    "Staff",
    "Principal",
    "Lead",
    "Distinguished",
    "Expert",
    "Architect",
    "II",
    "III",
    "IV",
  ],
  // Phrases (title or description) that clearly signal entry-level → kept.
  entrySignals: [
    "new grad",
    "new-grad",
    "entry level",
    "entry-level",
    "recent graduate",
    "recent grad",
    "early career",
    "early-career",
    "university graduate",
    "university grad",
    "graduate engineer",
    "graduate program",
    "campus hire",
    "junior",
    "associate",
    "apprentice",
    "0-1 years",
    "0-2 years",
    "no prior experience",
    "no experience required",
  ],
};
