import type { Application } from "./types";

/**
 * Demo rows shown on first load so the dashboard isn't empty.
 * Cleared the moment the user adds their own or hits "Clear all".
 */
export function sampleApplications(): Application[] {
  const id = () =>
    typeof crypto !== "undefined" && crypto.randomUUID
      ? crypto.randomUUID()
      : Math.random().toString(36).slice(2);

  return [
    {
      id: id(),
      company: "Stripe",
      role: "Software Engineer, Backend",
      location: "Bengaluru, India",
      source: "Greenhouse",
      dateApplied: "2026-07-02",
      referral: true,
      referrer: "Aarav Mehta",
      status: "interview",
      ctc: "₹48 LPA",
      link: "https://stripe.com/jobs",
      followUp: "2026-07-24",
      notes: "Onsite loop scheduled. Prep system design.",
    },
    {
      id: id(),
      company: "Razorpay",
      role: "SDE II",
      location: "Remote (India)",
      source: "LinkedIn",
      dateApplied: "2026-07-08",
      referral: false,
      referrer: "",
      status: "oa",
      ctc: "₹36 LPA",
      link: "",
      followUp: "2026-07-23",
      notes: "HackerRank OA due this week.",
    },
    {
      id: id(),
      company: "Atlassian",
      role: "Backend Engineer",
      location: "Bengaluru, India",
      source: "Lever",
      dateApplied: "2026-06-20",
      referral: true,
      referrer: "Priya Nair",
      status: "offer",
      ctc: "₹54 LPA",
      link: "",
      followUp: "",
      notes: "Offer received — negotiating.",
    },
    {
      id: id(),
      company: "Zomato",
      role: "Software Development Engineer",
      location: "Gurugram, India",
      source: "Naukri",
      dateApplied: "2026-06-15",
      referral: false,
      referrer: "",
      status: "rejected",
      ctc: "",
      link: "",
      followUp: "",
      notes: "Rejected after phone screen.",
    },
    {
      id: id(),
      company: "Google",
      role: "SWE II, Payments",
      location: "Hyderabad, India",
      source: "Company Site",
      dateApplied: "2026-07-12",
      referral: true,
      referrer: "Rohan Gupta",
      status: "applied",
      ctc: "",
      link: "",
      followUp: "2026-07-21",
      notes: "Referral submitted via internal portal.",
    },
    {
      id: id(),
      company: "Uber",
      role: "Backend Engineer II",
      location: "Bengaluru, India",
      source: "LinkedIn",
      dateApplied: "2026-06-28",
      referral: false,
      referrer: "",
      status: "ghosted",
      ctc: "",
      link: "",
      followUp: "",
      notes: "No response in 3+ weeks.",
    },
    {
      id: id(),
      company: "Notion",
      role: "Product Engineer",
      location: "Remote",
      source: "Wellfound",
      dateApplied: "",
      referral: false,
      referrer: "",
      status: "wishlist",
      ctc: "",
      link: "https://notion.so/careers",
      followUp: "",
      notes: "Dream role — tailor resume before applying.",
    },
  ];
}
